packages:
  - '.'

allowBuilds:
  sharp: true
  unrs-resolver: true

# setting the minimum release age to 5 days (7200 minutes) to ensure that releases are stable before being used in the workspace
minimumReleaseAge: 7200
blockExoticSubdeps: true
minimumReleaseAgeStrict: true # tracked in https://github.com/pnpm/pnpm/issues/11238