name: Rebuild website

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *' 

jobs:
  add-empty-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Add empty commit
      run: "git commit -m 'release: :rocket: rebuild website' --allow-empty --no-verify"
      
    - name: Push to repo
      run: "git push origin main" 
