name: rebuild-website

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *' 

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: release: :rocket: rebuild website
        branch: main
        add_options: '-u'
        commit-options: '--allow-empty --no-verify'
        skip_dirty_check: true
        push_options: '--force'
