name: Run checks

on:
  - push

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint:strict

  # tsc:
  #   name: Run Type Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         cache: 'pnpm'
  #     - run: pnpm install --pure-lockfile 
  #     - run: pnpm typecheck

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - run: pnpm install --pure-lockfile
      - run: pnpm format:check

  # test:
  #   name: Run Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         cache: 'pnpm'
  #     - run: pnpm install --pure-lockfile
  #     - run: pnpm test
