name: Update Counters

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */10 * * *'

jobs:
  update-counters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install ---pure-lockfile

      - name: Create environment file
        run: |
          touch .env.local
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env.local
          echo MONGODB_DB=${{ secrets.MONGODB_DB }} >> .env.local

      - name: Update counters
        run: yarn update-counters
