name: Update Image Metadata

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-counters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Install additional dependencies
        run: yarn add plaiceholder probe-image-size sharp

      - name: Create environment file
        run: |
          touch .env.local
          echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env.local
          echo MONGODB_DB=${{ secrets.MONGODB_DB }} >> .env.local

      - name: Update image metadata
        run: yarn update-image-metadata
